### ISSUE TITLE
Bugfix: Homepage with Cover Block and Hero keeps small-margins

### ISSUE THREAD

**Issue by svenbrier** [elmastudio/aino-theme#128]
Hi Ellen, thank you for the Aino Theme!

I added a Cover Block to my homepage and on top of it I inserted the Aino Hero Block.

On mobile the Cover isn't shown in full width, it has small-margins.

<img width="376" alt="Bildschirmfoto 2020-10-02 um 21 33 28" src="https://user-images.githubusercontent.com/8099264/94962621-07d89600-04f7-11eb-9121-d5e75a0b6146.png">

**Comment by ellenbauer** [comment]
Thanks so much for reporting and including a screenshot. That is super helpful :)
I fixed this issue in the latest theme version 1.2.2. Will upload this version to WP.org today and hopefully the review there won't take too long.
