### ISSUE TITLE
Multiple alignfull elements cause a horizontal scrollbar show up

### ISSUE THREAD

**Issue by 2ndkauboy** [elmastudio/aino-theme#131]
When more than one alignfull element is placed on a page, a horizontal scrollbar will how up. If one of the elements is removed, the scrollbar disappears again.

**Comment by ellenbauer** [comment]
Thanks for letting me know. I tried to recreate the issue but could not see it. Could you let me know in what screen size this happens and in which browser? Also did you test this with just 2 standard blocks, e.g. Full-width Group blocks?

Thanks so much for your help.

**Comment by 2ndkauboy** [comment]
Here you can see a test with to Cover blocks: https://bernhardkau.de/alignfull-test/
It also happens with Group blocks: https://bernhardkau.de/alignfull-groups/

The test is done on the latest commit of Aino (05ac41b).
