### ISSUE TITLE
Sitcky posts have css issues in headings

### ISSUE THREAD

**Issue by raaphorst** [elmastudio/aino-theme#149]
see screenshot from customizer:

<img width="1085" alt="Schermafbeelding 2021-02-12 om 09 56 21" src="https://user-images.githubusercontent.com/307039/107747950-97e5e200-6d18-11eb-9416-f3545e1ad92e.png">

**Comment by raaphorst** [comment]
another style issue: related links are not aligned in the right way:

![Uploading Schermafbeelding 2021-02-12 om 09.58.42.png…]()

**Comment by raaphorst** [comment]
another style issue: related links are not aligned in the right way:

<img width="1440" alt="Schermafbeelding 2021-02-12 om 09 58 42" src="https://user-images.githubusercontent.com/307039/107748243-03c84a80-6d19-11eb-9dc3-61d651aa0f96.png">

**Comment by ellenbauer** [comment]
Thanks so much for letting me know, I will fix the sticky post in the next theme update.

Regarding the related posts: Are they generated via a plugin? The theme comes with custom related posts. Could you check them and try to deactivate (I think it looks like Jetpack related posts)?

**Comment by raaphorst** [comment]
I am now trying on a blog where I can disable Jetpack and test. But now I am getting a critical error warming when previewing theme in the Customizer, a links sends me to https://wordpress.org/support/article/debugging-in-wordpress/

**Comment by ellenbauer** [comment]
Fixed in 1.3.1
