### ISSUE TITLE
Footer - No Space after fullstop

### ISSUE THREAD

**Issue by elbsegler63** [elmastudio/aino-theme#173]
![Footer_1](https://user-images.githubusercontent.com/85250773/121810087-b1b01b00-cc5f-11eb-819a-2883d8e4d5f7.JPG)

Between the site title and "powerd by"  is no space. Is the fullstop  required?

**Comment by elbsegler63** [comment]
Hi, the same (missing space) in the title of the category-page. Oder liege ich falsch?
![category-site](https://user-images.githubusercontent.com/85250773/121812536-7b2ace00-cc68-11eb-97bc-adbd23cf0e4a.JPG)

**Comment by ellenbauer** [comment]
Thanks for letting me know, I fixed this issue and the fix will be live in the next 1.4.0 update.
