### ISSUE TITLE
Uncentered featured small image in posts

### ISSUE THREAD

**Issue by joanpla** [elmastudio/aino-theme#19]
Small images appear uncentered on wide screens (more than 730 px aprox).

Ex (a 600x400 featured image):

![image](https://user-images.githubusercontent.com/22705173/61768844-d9d2ce80-ade8-11e9-9184-51a14b03c014.png)

**Comment by ellenbauer** [comment]
Thanks for reporting this, I fix it in the next update (0.0.4).
