### ISSUE TITLE
Ein Fehler vom Typ E_PARSE

### ISSUE THREAD

**Issue by fschmittlein** [elmastudio/aino-theme#2]
Nach dem aktivieren bekomme ich über den Wiederherstellungsmodus folgende Meldung:

Fehler-Details
==============
Ein Fehler vom Typ E_PARSE wurde in der Zeile 132 der Datei /html/.../htdocs/wp-content/themes/aino/inc/template-tags.php verursacht. Fehlermeldung: syntax error, unexpected ')'

**Comment by HDValentin** [comment]
Vielleicht hat es damit zu tun. Wenn ich einen Live Vorschau mache oder das Theme aktiviere bekomme ich die Meldung "Die Website hat technische Schwierigkeiten. Bitte das E-Mail-Postfach des Website-Administrators prüfen, um dort weitere Anweisungen zu finden."

**Comment by fschmittlein** [comment]
@HDValentin Ja, hat es. Ist bei mir auch so

**Comment by lisia123** [comment]
... und so ist's auch bei mir ... auch wenn ich die aktualisierte wpgulp.config.js hochgeladen habe.
LG

**Comment by ellenbauer** [comment]
Danke für die Fehlermeldung. Ich habe gerade ein Update vorbereitet. Es war ein Bug in der edit button function. Jetzt sollte die Installation problemlos funktionieren. Ich hoffe euch gefällt der Anfang :)

**Comment by ellenbauer** [comment]
Issue is fixed in version 0.0.2.
