### ISSUE TITLE
V2.4.3 shatters the header

### ISSUE THREAD

**Issue by Xanoris** [elmastudio/aino-theme#201]
V2.4.3 shatters the header for me. It is suddenly much too wide, everything is underneath each other instead of next to each other and the background color of the submenus is suddenly white again (it was before and should be dark blue again).
Shattered Header:
![aino_243_shattered-header](https://user-images.githubusercontent.com/84472000/132682008-12eb7b95-1c01-4a35-9d47-3af6aaa0cf47.png)

Submenu-Background:
![Bild_2021-09-09_140346](https://user-images.githubusercontent.com/84472000/132682400-04456795-d4a5-4394-b749-5b4212c4b329.png)

**Comment by ellenbauer** [comment]
Please update to the theme update 2.4.4 . Does it work better now?

**Comment by Xanoris** [comment]
Almost. By the update to V2.4.4 on the Frontend everything is arranged correctly again (in the Editor the contents are still below each other), it is now "only" too wide:
![aino_244_header-too-wide_Full-Width](https://user-images.githubusercontent.com/84472000/132703895-cf540d55-b0a3-44e3-8e92-770f380f9b09.png)

**Comment by Xanoris** [comment]
Something seems to be wrong with the spacing in general. Also, the card block on the home page of my website (the one with the quotes) is bursting at the seams: https://www.x-page.de.

And on smaller screens, the spacing from the left is missing in the texts:
![aino_244_text-align_extreme-left](https://user-images.githubusercontent.com/84472000/132716797-2981b7e5-818b-48f7-9b9d-ce6d498aebf4.png)

**Comment by Xanoris** [comment]
I was able to solve the block width issue with some additional CSS (for me), so I no longer have a scroll bar at the bottom:
`/* Fix für die Blockbreite */body`
body {
  --global--content--padding--left: 0.8rem;
  --global--content--padding--right: 4.68rem;
}

.wp-block-group.alignfull>.alignfull, [class*=wp-container-]>.alignfull {
    width: calc(96% + var(--global--content--padding--left) + var(--global--content--padding--right))!important;
}

**Comment by Xanoris** [comment]
I was able to solve the block width issue with some additional CSS, so there is no longer a scroll bar at the bottom:
```
html,
body {
overflow-x: hidden;
}
```

**Comment by Xanoris** [comment]
I think this is solved.
