### ISSUE TITLE
Block width not adjustable

### ISSUE THREAD

**Issue by Xanoris** [elmastudio/aino-theme#204]
You can no longer influence the width of the blocks used. No matter if you set it to "Full width" or not, it always stays at "Wide width" in the Frontend, in the Editor the width changes properly.

**Comment by ellenbauer** [comment]
I'm working on a fix there. I'm not 100% sure where the issue comes from, I think it's related to the latest Gutenberg plugin update. But I'm sure I can find a solution in the next theme update.

**Comment by ellenbauer** [comment]
This issue should not be relevant in the current theme version 2.6.5 and was related to a previous Gutenberg plugin issue,
