### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by Xanoris** [elmastudio/aino-theme#205]
My browser reports a missing file or a loading error:
`DevTools failed to load source map: Could not load content for https://path/to/my/page/wp-content/themes/aino/assets/build/css/main.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by ellenbauer** [comment]
I updated to Webpack and the map file is just a hidden file. Is the error message active in the latest 2.4.5 issue?

**Comment by Xanoris** [comment]
I don't know - there's no Update showing up. Still 2.4.4.

**Comment by Xanoris** [comment]
@ellenbauer it still exists in 2.4.5.
