### ISSUE TITLE
Improve email validator in comments

### ISSUE THREAD

**Issue by joanpla** [elmastudio/aino-theme#21]
The behaviour of the email validator in the comments is poor (an unstyled error message ("ERROR: please enter a valid email address") shows up in a new window).

**Comment by ellenbauer** [comment]
This is the default WordPress behaviour.

**Comment by ellenbauer** [comment]
Comments will be improved but since Aino 2+ the Comments block is uses so this issue can be closed. New improvements will be made for the Comments block once this block is further developed by the Gutenberg team.
