### ISSUE TITLE
Aino Spacing padding settings not visible on backend

### ISSUE THREAD

**Issue by tomfinitely** [elmastudio/aino-theme#221]
Using Aino Theme 2.6.3 with all the default plugins, the Aino Spacing padding doesn't render (or at least render consistently) for Grids, Grid Items, or paragraph blocks.
<img width="1774" alt="Screen Shot 2022-05-25 at 2 52 30 PM" src="https://user-images.githubusercontent.com/2481417/170346496-2cb38180-d03f-4784-96bb-06b9bef7f46c.png">

**Comment by ellenbauer** [comment]
@electricbrick Thanks so much for reporting this. I'm preparing the 2.6.4 theme release for Friday, and I will check the editor again to make sure everything is WordPress 6 ready.
