### ISSUE TITLE
Respect sticky posts in posts per page count

### ISSUE THREAD

**Issue by MarcJandt** [elmastudio/aino-theme#37]
Needs custom action to manipulate query.

**Comment by ellenbauer** [comment]
I think this should be fixed since 1.0.1. Could you check this again?

**Comment by MarcJandt** [comment]
Sorry for being so unspecific. In general WordPress adds sticky posts from other pages to the first page and would break a clean grid layout. In the following screenshot (posts per page is set to 6) post 5 (would already be placed on page 1) and post 11 as featured posts are leading to 7 posts on the first page, breaking the desired 3 x 2 grid.
![sticky_posts](https://user-images.githubusercontent.com/21021769/80474588-ec65cf80-8947-11ea-89cd-04ec2a7606d9.png)
I've created some working code and will upload it soon. By design it only works if the count of sticky posts is smaller than the posts per page setting.

**Comment by ellenbauer** [comment]
Issue is irrelevant since Aino 2.0 block update.
