### ISSUE TITLE
Double Publishdate in Blogcards

### ISSUE THREAD

**Issue by HDValentin** [elmastudio/aino-theme#42]
![PublishDate](https://user-images.githubusercontent.com/1276955/63102239-0a86cd80-bf7b-11e9-91b2-c36d0bab4247.jpg)

In the Blog view there are double date entries. 
I think it is the publish date and the last saved date.

The URL is https://happy-heidelberg.de/teamblog/
Themeversion ist 0.0.5

On some Blog-Cards I have the estimated time to read.

![PublishDate2](https://user-images.githubusercontent.com/1276955/63102554-a9132e80-bf7b-11e9-94db-fdc86cf98fd7.jpg)

**Comment by BinaryMoon** [comment]
This happens because of the `wp_kses_post` escaping the post time in the `aino_entry_date_blog` function.

I don't think wp_kses_post is needed. All of the data is escaped before it's inserted so I would remove it.
