### ISSUE TITLE
YouTube Videos: space before Video

### ISSUE THREAD

**Issue by HDValentin** [elmastudio/aino-theme#59]
When I embed Videos from YouTube there is a huge gap between the Video and the block before.
![youTube](https://user-images.githubusercontent.com/1276955/65822220-729a2600-e240-11e9-9a15-bbe0cc493e01.jpg)

Example: https://happy-heidelberg.de/heidelberg-happy-video-projekt/happy-heidelberg-videos/

**Comment by ellenbauer** [comment]
Just tested and the issue is fixed.
