### ISSUE TITLE
Default image for articles with no main image

### ISSUE THREAD

**Issue by HDValentin** [elmastudio/aino-theme#6]
It would be great, if there is a default image is shown if there is no main image in a blog article.
See at https://happy-heidelberg.de/teamblog/
![happyheidelberg](https://user-images.githubusercontent.com/1276955/61655523-05599a00-acbf-11e9-9f38-e761e9aa7b0a.jpg)
#featurerequest

**Comment by ellenbauer** [comment]
I see what you mean, I will think of a solution.

Would you like the alternative idea of making the posts without images shorter and not as long in height as the other posts in the row?

Also you would need to set a default value for the excerpt text in the Customizer under Theme / Blog Cards. There is still a bug in the code so the default value of 15 words for excerpts on blog cards is not visible. I'm working on a fix for this. I just saw the empty ellipsis, so I wanted to mention it :)

**Comment by MarcJandt** [comment]
There are plugins available like https://wordpress.org/plugins/default-featured-image/
I don't think this functionality should be implemented, but maybe a placeholder pattern without any options for users would be nice, so by default the posts page doesn't look broken and then the user can decide to place custom featured images or use a plugin for a default one.

**Comment by HDValentin** [comment]
Yes, this is a solution for this problem.
