### ISSUE TITLE
Abstandsangaben im Footer Bereich 

### ISSUE THREAD

**Issue by christopherkurth** [elmastudio/aino-theme#61]
![Bildschirmfoto 2019-10-01 um 00 18 53](https://user-images.githubusercontent.com/6201049/65921385-5f26c080-e3e2-11e9-8c2e-18dc0277124b.png)
![Bildschirmfoto 2019-10-01 um 00 21 36](https://user-images.githubusercontent.com/6201049/65921386-5fbf5700-e3e2-11e9-8a70-3bdbceeebe65.png)

Bei kleineren Displayauflösungen fehlt etwas Abstand zum Footer Text wie in den Bildern zu sehen.

![Bildschirmfoto 2019-10-01 um 00 24 31](https://user-images.githubusercontent.com/6201049/65921388-5fbf5700-e3e2-11e9-985a-1fc3f3c58b02.png)
![Bildschirmfoto 2019-10-01 um 00 25 25](https://user-images.githubusercontent.com/6201049/65921390-60f08400-e3e2-11e9-819b-fa79c91786a6.png)

Sobald die Footer-Infos zentrieren sind fehlen an den Satz enden Leerzeichen und die mobilen Ansicht mag es überhaupt nicht.

**Comment by ellenbauer** [comment]
Fixed :)
