### ISSUE TITLE
Feature: Edit Footer Credit

### ISSUE THREAD

**Issue by HDValentin** [elmastudio/aino-theme#70]
I would like to have the option to edit the footer credit line in Customizer:
![aino footer](https://user-images.githubusercontent.com/1276955/74602981-a7ebc700-50ae-11ea-9e38-9b958a212ac1.jpg)

https://happy-heidelberg.de/ Version 0.1.0

**Comment by ellenbauer** [comment]
We will definitely add this option. Thanks for adding the issue.
