### ISSUE TITLE
Bug; Menu is not Working corecct

### ISSUE THREAD

**Issue by HDValentin** [elmastudio/aino-theme#71]
I have this issue on my site at: https://happy-heidelberg.de/ Aino Version 0.1.0
Only on **Desktop**. Testet with Firefox and Edge.

On the startpage and on "Team" the menu is not flying out on mouseover.

Only when I am on "Blog" the submenu is working correct:
https://happy-heidelberg.de/teamblog/

**Comment by ellenbauer** [comment]
I fixed this issue already. Can you try the current theme version 0.2.0?

**Comment by HDValentin** [comment]
Yes it is working correct in Version 0.2.0
Thank you!
