### ISSUE TITLE
2nd logo option for hero page template

### ISSUE THREAD

**Issue by mschache** [elmastudio/aino-theme#80]
Hi Ellen, I tapped into the problem that we use a black logo on most of the pages but would need a white one for our hero pages. For now, we solved it with fullscreen but I would prefer to have the logo and menu on the hero.  

Thanks and lots of love from Germany

**Comment by ellenbauer** [comment]
Hi @mschache ,
I'm super sorry for my late response. we ran into the same issue and considered adding a second logo image option. 

Then I thought it's even better to use an SVG image instead and apply colours with CSS (using page template classes or even the page id's).

I solved this with the "SVG support" plugin. Do you think this could also be a solution in your case? Let me know if you need further help to get this working.

**Comment by ellenbauer** [comment]
Issue is not relevant any longer since multiple block Header template parts can be used to solve the issue since the Aino 2+ version.
