### ISSUE TITLE
Add "back to top" button (optional)

### ISSUE THREAD

**Issue by ellenbauer** [elmastudio/aino-theme#88]

**Comment by 2ndkauboy** [comment]
I'd says that's plugin territory but as an optional (Customizer) setting, I wouldn't say no to a nicely styled "back to top" button. Just make sure it's not hurting frontend performance ;)

https://kau-boys.de/2076/webentwicklung/javascript-performance-bei-scroll-event-handlern-verbessern

**Comment by ellenbauer** [comment]
Added in theme update 1.2.0
